
# Site settings
title: Festival Universitaire Ludique Libre
email: abl@univ-lille.fr
url: http://bidouilleurslibristes.github.io/
description: "
Le Festival Universitaire Ludique Libre <br> 2 Février 2019 - Cité Scientifique - Université de Lille
<p>Une journée consacrée au(x) jeu(x) libre(s) ou indépendant(s), proposés par l'Association des Bidouilleurs Libristes. L'objectif est de promouvoir le « libre » au sens large par et/ou pour le(s) jeu(x).</p>"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Bidouilleurs Libristes

# # Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#   - title: twitter
#     url: https://twitter.com/SBootstrap
#- title: facebook
 #    url: https://www.facebook.com/events/1167616406722612/
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
